name: Node.js CSV Parser CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # tested only on 20

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --force
    - run: npm run build --if-present

    - name: Create uploads folder
      run: mkdir -p dist/uploads

    - run: npm test

    - name: Add remote host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SiGiRi_SSH_PORT }} ${{ secrets.SiGiRi_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SiGiRi_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SiGiRi_SSH_HOST }}
        SSH_USER: ${{ secrets.SiGiRi_SSH_USER }}
        SSH_PORT: ${{ secrets.SiGiRi_SSH_PORT }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key -p $SSH_PORT" --exclude node_modules ./ $SSH_USER@$SSH_HOST:/home/ubuntu/csv-parser
        ssh -i private_key -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/ubuntu/csv-parser
          npm install --production
          mkdir -p uploads
          pm2 restart csv-parser || pm2 start npm --name "csv-parser" -- start
          exit
        EOF
      shell: bash
